<?php

use Illuminate\Database\Seeder;

class SectorTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {




        DB::table('sectors')->insert([
            'name' => "Energy",
            'description' => "The energy sector consists of oil and gas exploration and production companies, as well as integrated power firms, refineries and other operations. In general, these companies generate revenue that’s tied to the price of crude oil, natural gas and other commodities.",
            'user_id' => 1,
            'id' => "9792d8d8-2673-4f09-bf1c-465344d93ec2",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industry_groups')->insert([
            'name' => "Energy",
            'description' => "The energy sector consists of oil and gas exploration and production companies, as well as integrated power firms, refineries and other operations. In general, these companies generate revenue that’s tied to the price of crude oil, natural gas and other commodities.",
            'sector_id' => '9792d8d8-2673-4f09-bf1c-465344d93ec2',
            'user_id' => 1,
            'id' => "4158372b-a3a1-4787-9e23-955d462270db",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Energy Equipment & Services",
            'description' => "The energy sector consists of oil and gas exploration and production companies, as well as integrated power firms, refineries and other operations. In general, these companies generate revenue that’s tied to the price of crude oil, natural gas and other commodities.",
            'industry_group_id' => '4158372b-a3a1-4787-9e23-955d462270db',
            'user_id' => 1,
            'id' => "e173aa7d-a7e6-4434-ab13-d0868878e2be",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);









































        DB::table('sectors')->insert([
            'name' => "Financial",
            'description' => "The financial sector consists of banks, investment funds, insurance companies and real estate firms, among others. In general, the majority of the revenue generated by the sector comes from mortgages and loans that gain value as interest rates rise.",
			'user_id' => 1,
			'id' => "b9955af7-6be4-4fd8-ad93-8f85e9bac4c3",
			'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
		]);

	    DB::table('sectors')->insert([
            'name' => "Utility",
            'description' => "The utilities sector consists of electric, gas and water companies as well as integrated providers. In general, the sector generates consistent recurring income by charging consumers and businesses that provide higher-than-average dividend yields.",
			'user_id' => 1,
			'id' => "d7c7f2e5-1a74-4d79-b833-ca6d215b2d38",
			'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
		]);

	    DB::table('sectors')->insert([
            'name' => "Consumer discretionary",
            'description' => "The consumer discretionary sector consists of retailers, media companies, consumer service providers, apparel companies and consumer durables. In general, these companies benefit from an improving economy when consumer spending accelerates.",
			'user_id' => 1,
			'id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
			'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
		]);

	    DB::table('sectors')->insert([
            'name' => "Consumer Staples",
            'description' => "The consumer staples sector consists of food and beverage companies as well as companies that create products consumers are unwilling to cut from their budgets. In general, these companies are defensive plays capable of withstanding an economic downturn.",
			'user_id' => 1,
			'id' => "c4104fa4-59f5-435a-a717-5c4631e38cb3",
			'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
		]);

	    DB::table('sectors')->insert([
            'name' => "Healthcare",
            'description' => "The health care sector consists of biotechnology companies, hospital management firms, medical device manufacturers and many others. In general, the sector is considered to be both a growth opportunity and defensive play since people will always require medical aid.",
			'user_id' => 1,
			'id' => "006ad96d-7322-4d7d-bb50-808001302afd",
			'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
		]);

	    DB::table('sectors')->insert([
            'name' => "Industrial",
            'description' => "The industrial sector consists of aerospace, defense, machinery, construction, fabrication and manufacturing companies. In general, the industry’s growth is driven by demand for building construction and manufactured products like agricultural equipment.",
			'user_id' => 1,
			'id' => "84fa15d5-d769-4e1c-8739-9016d1c58615",
			'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
		]);

	    DB::table('sectors')->insert([
            'name' => "Technology",
            'description' => "The technology sector consists of electronics manufacturers, software developers and information technology firms. In general, these businesses are driven by upgrade cycles and the general health of the economy, although growth has been robust over the years.",
			'user_id' => 1,
			'id' => "44dfe6cd-5a47-478d-b3fe-35385b405780",
			'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
		]);

	    DB::table('sectors')->insert([
            'name' => "Telecom",
            'description' => "The telecom sector consists of wireless providers, cable companies, internet service providers and satellite companies, among others. In general, these companies generate recurring revenue from consumers, but some subsets of the industry are facing rapid change.",
			'user_id' => 1,
			'id' => "1d86ebd1-2312-4124-9a50-cc4d53a3e187",
			'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
		]);

	    DB::table('sectors')->insert([
            'name' => "Materials",
            'description' => "The materials sector consists of mining, refining, chemical, forestry and relatitudeed companies that are focused on discovering and developing raw materials. Since these companies are at the beginning of the supply chain, they are vulnerable to changes in the business cycle.",
            'user_id' => 1,
            'id' => "54cc4048-a8e2-42ca-ac1f-1a0fa414bf42",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

	    DB::table('sectors')->insert([
            'name' => "Real estate",
            'description' => "The real estate sector consists of companies invested in residential, industrial, and retail real estate. The main source of revenue for these companies comes from rent income and real estate capital appreciation. As a result, this sector is sensitive to interest rate changes.",
            'user_id' => 1,
            'id' => "dbb90696-2772-4875-8f24-7eef330be58f",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

































        ### Financial sector industries
        DB::table('industries')->insert([
            'name' => "Bank",
            'description' => "A bank is a financial institution that accepts deposits from the public and creates credit. Lending activities can be performed either directly or indirectly through capital markets.",
            'sector_id' => "b9955af7-6be4-4fd8-ad93-8f85e9bac4c3",
            'user_id' => 1,
            'id' => "06c4b0a3-c43e-4e44-b60f-8f278c4951c3",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Investment fund",
            'description' => "An investment fund is a supply of capital belonging to numerous investors used to collectively purchase securities while each investor retains ownership and control of his own shares.",
            'sector_id' => "b9955af7-6be4-4fd8-ad93-8f85e9bac4c3",
            'user_id' => 1,
            'id' => "6c03e7d1-f90b-4b85-aae4-5d3916cacbeb",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Insurance",
            'description' => "Insurance is a means of protection from financial loss. It is a form of risk management, primarily used to hedge against the risk of a contingent or uncertain loss.",
            'sector_id' => "b9955af7-6be4-4fd8-ad93-8f85e9bac4c3",
            'user_id' => 1,
            'id' => "c66c7038-90ca-4c64-bcd4-56cbb5a3f424",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

	    DB::table('industries')->insert([
            'name' => "Real estate",
            'description' => "The residential sector focuses on the buying and selling of properties used as homes or for non-professional purposes. The commercial sector consists of real estate used for business purposes; common types include retail and office space.",
            'sector_id' => "b9955af7-6be4-4fd8-ad93-8f85e9bac4c3",
            'user_id' => 1,
            'id' => "92db9f6f-6807-46cf-a6ad-49e39ca968af",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

	    ### Consumer discretionary sector industries
        DB::table('industries')->insert([
            'name' => "Water",
            'description' => "The water industry is made up of the regulated water utility companies, non-regulated subsidiary water companies (e.g. involved in construction, engineering, consultancy, laboratory services, etc) and the associated supply chain. Together they are responsible for the supply of clean water to customers up to and including the internal stop valve on the customer’s property and the collection and treatment of waste water.",
            'sector_id' => "d7c7f2e5-1a74-4d79-b833-ca6d215b2d38",
            'user_id' => 1,
            'id' => "4fc4e3bd-b7c8-4c1d-8374-6bfb52c46c21",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Gas (upstream)",
            'description' => "Upstream gas consists of the transportation of gas from beach terminals through the National Transmission System, into the Local Distribution System, and then up to, and including, the main control valve adjacent to the customers property.",
            'sector_id' => "d7c7f2e5-1a74-4d79-b833-ca6d215b2d38",
            'user_id' => 1,
            'id' => "ec322212-259c-48b6-b63c-8d62d8cd7c49",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Gas (downstream)",
            'description' => "The gas downstream sub-sector consists of all activities that take place on the customer’s side of the main control valve (including the meter) such as installation and maintenance of central heating systems and other gas appliances.",
            'sector_id' => "d7c7f2e5-1a74-4d79-b833-ca6d215b2d38",
            'user_id' => 1,
            'id' => "d59f0f86-726c-4df3-afa8-af2a89af5eea",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Power",
            'description' => "The power industry covers the activities associated with the generation, transmission and distribution of power. It is dominated by a relatively small number of large organisations. There is free market competition between the organisations.",
            'sector_id' => "d7c7f2e5-1a74-4d79-b833-ca6d215b2d38",
            'user_id' => 1,
            'id' => "026fc767-5646-4a9a-b629-f16425f79834",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Waste management",
            'description' => "The waste management industry is primarily concerned with the collection, transport, treatment and final management of waste and recyclables. Once waste is generated from other sectors of the economy, it is collected and passed through a series of processes, resulting in a valuable or non-valuable output. Non-valuable outputs consist of materials that are either sent to landfill or incinerated to produce energy, heat or power. Valuable outputs are dismantled, sorted and then recycled into new products.",
            'sector_id' => "d7c7f2e5-1a74-4d79-b833-ca6d215b2d38",
            'user_id' => 1,
            'id' => "026fc767-5646-4a9a-b629-f16425f79834",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

	    ### Consumer discretionary sector industries
        DB::table('industries')->insert([
            'name' => "Auto Components Industry",
            'description' => "The automobile and components industry group includes companies that make cars and motorcycles as well as companies that make auto parts and tires.",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "92db9f6f-6807-46cf-a6ad-49e39ca968af",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Automobile Industry",
            'description' => "The automobile industry designs, produces and markets cars, trucks, buses and other types of vehicles.",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "b4e9af5a-3285-4e25-add6-5dca742c6e99",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Distributors Industry",
            'description' => "The distributors industry consists of companies that operate various channels for the distribution of a wide range of products and services, including consumer equipment products, apparel, replacement parts, wholesale consumer electronics and food.",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "18fbf8cc-bff2-445d-ad57-c8f6296e2676",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Diversified Consumer Services Industry",
            'description' => "The diversified consumer services industry includes companies that provide services, such as education, home security, legal advice, interior design and consumer auctions.",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "18fbf8cc-bff2-445d-ad57-c8f6296e2676",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Hotels, Restaurants and Leisure",
            'description' => "The hotels, restaurants and leisure industry comprises companies that operate hotels, fast food restaurants, resorts, casinos and cruises.",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "00439a24-feaa-4cfc-82fb-c71dc497abb5",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Household Durables",
            'description' => "The household durables industry manufactures products that cannot be consumed immediately and are bought only infrequently. Examples of household durable goods include lawn and garden equipment, home and office furnishings, appliances, photographic equipment and sporting goods. ",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "47944fc1-9873-48a1-9b55-f04bd6126c46",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Internet and Catalog Retail",
            'description' => "The internet and catalog retail has been one of the rapidly growing industries within the consumer discretionary sector, as consumer shifted to purchasing goods online. The industry includes companies that operate online marketplaces or their own online stores that sell a wide variety of consumer products.",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "50066029-18bd-4df6-a5dc-982fd396d805",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Leisure Products",
            'description' => "The leisure products industry consists of companies that cater towards consumers' leisure activities, such as sports, toys and various outdoor activities. Leisure goods include various camping equipment, toys, all-terrain vehicles and golf carts.",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "865e5ade-56eb-4203-a491-700f7a1f46e5",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

	    DB::table('industries')->insert([
            'name' => "Media",
            'description' => "The media industry provides various entertainment content for consumers, including movies, TV programming, newspapers, magazines and radio.",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "209bf29e-32d0-4008-a0ad-0319b64faf55",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Multiline Retail",
            'description' => "The multiline retail industry includes operators of department stores and other stores that sell general merchandise, such as hypermarkets and large-scale supercenters",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "54793f7f-0e05-474e-b8e7-6781d570494c",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Specialty Retail",
            'description' => "The specialty retail industry includes retail companies that specialize in selling specific categories of goods to consumers, such as apparel, electronics, home improvement, automotive retail and home furnishings.",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "366dcac9-26ca-4f65-8659-7af235f81c4a",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Textile, Apparel and Luxury Goods",
            'description' => "The textiles, apparel and luxury goods industry includes manufacturers of apparel merchandise, footwear and a wide variety of accessories, such as handbags, eyewear and travel-related goods.",
            'sector_id' => "b261396f-2bbc-4246-8cd3-685a32069b93",
            'user_id' => 1,
            'id' => "aafbdc1e-8415-4fcc-8e7b-a1da70b03702",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

	    # Consumer Staples sub sectors
        DB::table('industries')->insert([
            'name' => "Food and Staples Retailing",
            'description' => "The food and staples retailing industry group is broken into four main sub-industries: drug retail, food distributors, food retail and hypermarkets and supercenters.",
            'sector_id' => "c4104fa4-59f5-435a-a717-5c4631e38cb3",
            'user_id' => 1,
            'id' => "db779ade-8d9d-4d9b-b70b-867513d920ad",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Food, Beverage and Tobacco",
            'description' => "Food, beverage and tobacco includes companies that produce any sort of agricultural products, such as wheat; packaged foods, such as cheese; alcoholic and non-alcoholic beverages, such as soft drinks and beer and tobacco products, such as cigarettes. ",
            'sector_id' => "c4104fa4-59f5-435a-a717-5c4631e38cb3",
            'user_id' => 1,
            'id' => "7b5be528-cdc8-4785-93e8-88c28c816daa",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Household and Personal Products",
            'description' => "The household and personal products industry group includes companies that produce non-durable products such as soap, detergent, diapers, shampoo, and cosmetics. Non-durable refers to products that are repurchased regularly.",
            'sector_id' => "c4104fa4-59f5-435a-a717-5c4631e38cb3",
            'user_id' => 1,
            'id' => "ba1ec456-7f5b-4e44-895c-732270f99e74",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

	    # Energy
        DB::table('industries')->insert([
            'name' => "Renewable energy",
            'description' => "The renewable-energy industry is the part of the energy industry focusing on new and appropriate renewable energy technologies.",
            'sector_id' => "9792d8d8-2673-4f09-bf1c-465344d93ec2",
            'user_id' => 1,
            'id' => "44878a85-dd63-4614-98ae-0e094b746332",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Oil and Gas",
            'description' => "The industry is usually divided into three major components: upstream(finds and produces crude oil and natural gas), midstream(processes, stores, markets and transports commodities such as crude oil, natural gas, natural gas liquids) and downstream(includes oil refineries, petrochemical plants, petroleum products distributors, retail outlets and natural gas distribution companies)",
            'sector_id' => "9792d8d8-2673-4f09-bf1c-465344d93ec2",
            'user_id' => 1,
            'id' => "b64a0b01-8823-4e76-908e-139374c328c9",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Coal",
            'description' => "The industry deals with the extraction of coal.",
            'sector_id' => "9792d8d8-2673-4f09-bf1c-465344d93ec2",
            'user_id' => 1,
            'id' => "c36f2ba2-75db-4b2e-8c85-99bc916fb942",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Nuclear energy",
            'description' => "Nuclear power is the use of nuclear reactions that release nuclear energy to generate heat, which most frequently is then used in steam turbines to produce electricity in a nuclear power plant.",
            'sector_id' => "9792d8d8-2673-4f09-bf1c-465344d93ec2",
            'user_id' => 1,
            'id' => "3cdb75a4-5438-48a0-8141-100bdf1cb922",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

	    # Healthcare
        DB::table('industries')->insert([
            'name' => "Drugs",
            'description' => "Drug manufacturers can further be broken down into biotechnology firms, major pharmaceuticals firms, and makers of generic drugs.",
            'sector_id' => "9792d8d8-2673-4f09-bf1c-465344d93ec2",
            'user_id' => 1,
            'id' => "70bfdf2e-214c-4acc-abdd-b40017622f18",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Medical Equipment",
            'description' => "Medical equipment makers range from firms that manufacture standard, familiar products – scalpels, forceps, bandages, gloves – to those that conduct cutting-edge research and produce expensive, high-tech equipment such as MRI machines and surgical robots.",
            'sector_id' => "9792d8d8-2673-4f09-bf1c-465344d93ec2",
            'user_id' => 1,
            'id' => "c9d62754-f588-481f-b2d1-894dd9170554",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Managed Healthcare",
            'description' => "Managed healthcare companies provide health insurance policies.",
            'sector_id' => "9792d8d8-2673-4f09-bf1c-465344d93ec2",
            'user_id' => 1,
            'id' => "c9d62754-f588-481f-b2d1-894dd9170554",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);

        DB::table('industries')->insert([
            'name' => "Healthcare Facilities",
            'description' => "Health care facilities firms operate hospitals, clinics, labs, psychiatric facilities and nursing homes. ",
            'sector_id' => "9792d8d8-2673-4f09-bf1c-465344d93ec2",
            'user_id' => 1,
            'id' => "b960dddc-97a3-47f5-a0de-8de5a3bbe88d",
            'status_id' => 'c670f7a2-b6d1-4669-8ab5-9c764a1e403e',
        ]);


    }
}

